/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class CheckIn2_GUI extends javax.swing.JFrame {
      
    
    
    //------------
    static int cod;
    static String partI;
    static String destI;
    static String partV;
    static String destV;
    static String datI;
    static String horI;
    static String datV;
    static String horV;
    static String asse;
    static String clas;
    
    String url = "jdbc:mysql://localhost/VMAIRLANES"; // enderço do BD
    String username = "root";        //nome de um usuário de seu BD
    String password = "";  // senha do BD
    //-------------
    
    //código---
    
    public static DefaultTableModel  passagem_idavolta(ResultSet rs) {
        try {
           ResultSetMetaData metaData = rs.getMetaData();
         int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();
       // AS LINHAS ABAIXO SÃO REFERENTES AOS CAMPOS DA TABELA CLIENTE
            columnNames.addElement("Código");
            columnNames.addElement("Partida Ida");
            columnNames.addElement("Destino Ida");
            columnNames.addElement("Data Ida");
            columnNames.addElement("Hora Ida");
            columnNames.addElement("Partida Volta");
            columnNames.addElement("Destino Volta");
            columnNames.addElement("Data Volta");
            columnNames.addElement("Hora Volta");
            columnNames.addElement("Assento");
            columnNames.addElement("Classe");
         
            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
           return new DefaultTableModel(rows, columnNames);
       } catch (Exception e) {

           return null;
        }
        }

    
    //código---
    
    
    
    //codigo2---
    
    public void refresh(){
    
try{
   Connection conn;
          conn = (Connection) DriverManager.getConnection(url, username, password);
    //Controller.Conecta_BD.carregaDriver();
     
    
    System.out.println("realizado");
            String sql = "SELECT * FROM partida_idavolta;";
PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
ResultSet rs = pst.executeQuery();
//cliente.setModel(cliente(rs));
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}    
    } 

    
    //codigo2---
    
    
    
    public CheckIn2_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        destinoIda_che = new javax.swing.JTextField();
        partidaVolta_che = new javax.swing.JTextField();
        partidaIda_che = new javax.swing.JTextField();
        horaIda_che = new javax.swing.JTextField();
        destinoVolta_che = new javax.swing.JTextField();
        horaVolta_che = new javax.swing.JTextField();
        classe2_che = new javax.swing.JTextField();
        dataVolta_che = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dataIda_che = new javax.swing.JTextField();
        cod2_che = new javax.swing.JTextField();
        assento2_che = new javax.swing.JTextField();
        checkin2_BTN = new org.edisoncor.gui.button.ButtonIcon();
        nome2_che = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkinTela.png"))); // NOI18N
        panelImage1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Destino volta:");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(60, 230, 150, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Partida volta:");
        panelImage1.add(jLabel3);
        jLabel3.setBounds(440, 190, 140, 20);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data e hora volta:");
        panelImage1.add(jLabel4);
        jLabel4.setBounds(440, 240, 150, 20);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Partida ida:");
        panelImage1.add(jLabel5);
        jLabel5.setBounds(60, 110, 130, 20);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Destino ida:");
        panelImage1.add(jLabel6);
        jLabel6.setBounds(440, 110, 120, 20);
        panelImage1.add(destinoIda_che);
        destinoIda_che.setBounds(440, 130, 160, 20);
        panelImage1.add(partidaVolta_che);
        partidaVolta_che.setBounds(440, 210, 160, 20);
        panelImage1.add(partidaIda_che);
        partidaIda_che.setBounds(60, 130, 160, 20);
        panelImage1.add(horaIda_che);
        horaIda_che.setBounds(110, 180, 40, 20);
        panelImage1.add(destinoVolta_che);
        destinoVolta_che.setBounds(60, 250, 160, 20);
        panelImage1.add(horaVolta_che);
        horaVolta_che.setBounds(490, 260, 40, 20);
        panelImage1.add(classe2_che);
        classe2_che.setBounds(280, 330, 90, 30);
        panelImage1.add(dataVolta_che);
        dataVolta_che.setBounds(440, 260, 40, 20);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data e hora ida:");
        panelImage1.add(jLabel7);
        jLabel7.setBounds(60, 160, 130, 20);
        panelImage1.add(dataIda_che);
        dataIda_che.setBounds(60, 180, 40, 20);
        panelImage1.add(cod2_che);
        cod2_che.setBounds(480, 330, 50, 30);
        panelImage1.add(assento2_che);
        assento2_che.setBounds(80, 330, 50, 30);

        checkin2_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checin_img.png"))); // NOI18N
        checkin2_BTN.setText("buttonIcon1");
        checkin2_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkin2_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(checkin2_BTN);
        checkin2_BTN.setBounds(540, 330, 30, 30);

        nome2_che.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        nome2_che.setForeground(new java.awt.Color(255, 255, 255));
        nome2_che.setText("Luis Henrique");
        panelImage1.add(nome2_che);
        nome2_che.setBounds(260, 40, 350, 40);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 650, 400);

        setSize(new java.awt.Dimension(650, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkin2_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkin2_BTNActionPerformed
       Model.Funcionalidades_DAO.nomeCheckin2();


      //--------
        
        
        
        try{     //Iniciando o possivel tratamento de erros
            //Declarando a variavel código
            int codigo = Integer.valueOf(cod2_che.getText());
            Controller.Conecta_BD.carregaDriver(); // Carregando o driver
            try {// Tratamento de erro para a conexao
                // Declarando  a variavel de conexão con
                // e estabelendo a conexão
                Connection con = null;

                try {
                    con = (Connection) DriverManager.getConnection(url, username, password);
                } catch (SQLException ex) {
                    Logger.getLogger(CheckIn2_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }

                // Declarando uma string com o comando mySQL para consulta
                String sql = "SELECT partidaida_pas, partidavolta_pas, destinoida_pas, destinovolta_pas, dataida_pas, datavolta_pas, horaida_pas, horavolta_pas, assentos_pas, classe_pas FROM passagem_idavolta where cod_pas = "+codigo;
                // Criando variavel que executara o comando da string sql
                Statement stm = (Statement) con.createStatement();
                try//Tratamento de erro da consulta
                { //Criando variavel que exibira os resultados
                    //Executando o comando da string sql na variavel rs
                    ResultSet rs = stm.executeQuery(sql);

                    int i=0; // Variavel utilizada para saber se ha dados cadastrados

                    while (rs.next()) {  // Criando variaveis que receberão os valores do banco de dados
                        String partidaI = rs.getString("partidaida_pas");
                        String destinoI = rs.getString("destinoida_pas");
                        String dataI = rs.getString("dataida_pas");
                        String horaI = rs.getString("horaida_pas");
                        String partidaV = rs.getString("partidavolta_pas");
                        String destinoV = rs.getString("destinovolta_pas");
                        String dataV = rs.getString("datavolta_pas");
                        String horaV = rs.getString("horavolta_pas");
                        

                        i++;

                        //JOptionPane.showMessageDialog(null,"Nome: " + nome + "\nEmail: " +email + "\nTelefone: " +telefone, "Resultado",-1);
                        partidaIda_che.setText(String.valueOf(partidaI));
                        destinoIda_che.setText(String.valueOf(destinoI));
                        dataIda_che.setText(String.valueOf(dataI));
                        horaIda_che.setText(String.valueOf(horaI));
                        partidaVolta_che.setText(String.valueOf(partidaV));
                        destinoVolta_che.setText(String.valueOf(destinoV));
                        dataVolta_che.setText(String.valueOf(dataV));
                        horaVolta_che.setText(String.valueOf(horaV));
                        

                    }

                    if(i==0){ // Verificando se ha dados cadastrados atraves da variavel i

                        JOptionPane.showMessageDialog(null,"Dado não cadastrado","Resultado",-1);

                    }

                } catch (Exception ex) { // Consulta mal sucedida
                    JOptionPane.showMessageDialog(null,"\nErro ao consultar!","ERRO",0);
                }

            } catch (SQLException ex) {
                // Conexão com servidor mal sucedida
                JOptionPane.showMessageDialog(null,"Erro ao conectar com o servidor","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Código fora do formato
            JOptionPane.showMessageDialog(null,"Digite o código corretamante","ERRO",0);
            cod2_che.setText("");
        }
        
        
        
       //--------
    }//GEN-LAST:event_checkin2_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn2_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField assento2_che;
    private org.edisoncor.gui.button.ButtonIcon checkin2_BTN;
    public static javax.swing.JTextField classe2_che;
    private javax.swing.JTextField cod2_che;
    public static javax.swing.JTextField dataIda_che;
    public static javax.swing.JTextField dataVolta_che;
    public static javax.swing.JTextField destinoIda_che;
    public static javax.swing.JTextField destinoVolta_che;
    public static javax.swing.JTextField horaIda_che;
    public static javax.swing.JTextField horaVolta_che;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel nome2_che;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    public static javax.swing.JTextField partidaIda_che;
    public static javax.swing.JTextField partidaVolta_che;
    // End of variables declaration//GEN-END:variables
}
