/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class CheckIn_GUI extends javax.swing.JFrame {

    
    //------------
    static int cod;
    static String part;
    static String dest;
    static String dat;
    static String hor;
    static String asse;
    static String clas;
    static String nom;
    
    String url = "jdbc:mysql://localhost/VMAIRLANES"; // enderço do BD
    String username = "root";        //nome de um usuário de seu BD
    String password = "";  // senha do BD
    //-------------
    
    //código---
    
    public static DefaultTableModel  passagem_ida(ResultSet rs) {
        try {
           ResultSetMetaData metaData = rs.getMetaData();
         int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();
       // AS LINHAS ABAIXO SÃO REFERENTES AOS CAMPOS DA TABELA CLIENTE
            columnNames.addElement("Código");
            columnNames.addElement("Partida");
            columnNames.addElement("Destino");
            columnNames.addElement("Data");
            columnNames.addElement("Hora");
            columnNames.addElement("Assento");
            columnNames.addElement("Classe");
         
            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
           return new DefaultTableModel(rows, columnNames);
       } catch (Exception e) {

           return null;
        }
        }

    
    //código---
    
    
    
    //codigo2---
    
    public void refresh(){
    
try{
   Connection conn;
          conn = (Connection) DriverManager.getConnection(url, username, password);
    //Controller.Conecta_BD.carregaDriver();
     
    
    System.out.println("realizado");
            String sql = "SELECT * FROM partida_ida;";
PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
ResultSet rs = pst.executeQuery();
//cliente.setModel(cliente(rs));
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}    
    } 

    
    //codigo2---
    
   
    
    
    public CheckIn_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hora_che = new javax.swing.JTextField();
        checkin_BTN = new org.edisoncor.gui.button.ButtonIcon();
        cod1_che = new javax.swing.JTextField();
        destino_che = new javax.swing.JTextField();
        classe_che = new javax.swing.JTextField();
        partida_che = new javax.swing.JTextField();
        assento_che = new javax.swing.JTextField();
        data_che = new javax.swing.JTextField();
        nome_che = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkinTela.png"))); // NOI18N
        panelImage1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Destino:");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(430, 120, 90, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Partida:");
        panelImage1.add(jLabel3);
        jLabel3.setBounds(70, 110, 80, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data e hora:");
        panelImage1.add(jLabel4);
        jLabel4.setBounds(70, 200, 100, 20);
        panelImage1.add(hora_che);
        hora_che.setBounds(130, 220, 50, 20);

        checkin_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checin_img.png"))); // NOI18N
        checkin_BTN.setText("buttonIcon1");
        checkin_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkin_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(checkin_BTN);
        checkin_BTN.setBounds(540, 330, 30, 30);
        panelImage1.add(cod1_che);
        cod1_che.setBounds(480, 330, 50, 30);
        panelImage1.add(destino_che);
        destino_che.setBounds(430, 140, 150, 20);
        panelImage1.add(classe_che);
        classe_che.setBounds(280, 330, 90, 20);
        panelImage1.add(partida_che);
        partida_che.setBounds(70, 140, 150, 20);
        panelImage1.add(assento_che);
        assento_che.setBounds(80, 330, 50, 30);
        panelImage1.add(data_che);
        data_che.setBounds(70, 220, 50, 20);

        nome_che.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        nome_che.setForeground(new java.awt.Color(255, 255, 255));
        nome_che.setText("Luis Hneirque");
        panelImage1.add(nome_che);
        nome_che.setBounds(250, 40, 170, 30);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 650, 400);

        setSize(new java.awt.Dimension(650, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkin_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkin_BTNActionPerformed
        Model.Funcionalidades_DAO.nomeCheckin();


//--------
        
        
        
        try{     //Iniciando o possivel tratamento de erros
            //Declarando a variavel código
            int codigo = Integer.valueOf(cod1_che.getText());
            Controller.Conecta_BD.carregaDriver(); // Carregando o driver
            try {// Tratamento de erro para a conexao
                // Declarando  a variavel de conexão con
                // e estabelendo a conexão
                Connection con = null;

                try {
                    con = (Connection) DriverManager.getConnection(url, username, password);
                } catch (SQLException ex) {
                    Logger.getLogger(CheckIn_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }

                // Declarando uma string com o comando mySQL para consulta
                String sql = "SELECT partida_pas, destino_pas, data_pas, hora_pas, assentos_pas, classe_pas FROM passagem_ida where cod_pas = "+codigo;
                // Criando variavel que executara o comando da string sql
                Statement stm = (Statement) con.createStatement();
                try//Tratamento de erro da consulta
                { //Criando variavel que exibira os resultados
                    //Executando o comando da string sql na variavel rs
                    ResultSet rs = stm.executeQuery(sql);

                    int i=0; // Variavel utilizada para saber se ha dados cadastrados

                    while (rs.next()) {  // Criando variaveis que receberão os valores do banco de dados
                        String partida = rs.getString("partida_pas");
                        String destino = rs.getString("destino_pas");
                        String data = rs.getString("data_pas");
                        String hora = rs.getString("hora_pas");
                        

                        i++;

                        //JOptionPane.showMessageDialog(null,"Partida: " + partida + "\nDestino: " +destino + "\nData: " +data, "Resultado",-1);
                        
                        

                    }

                    if(i==0){ // Verificando se ha dados cadastrados atraves da variavel i

                        JOptionPane.showMessageDialog(null,"Dado não cadastrado","Resultado",-1);

                    }

                } catch (Exception ex) { // Consulta mal sucedida
                    JOptionPane.showMessageDialog(null,"\nErro ao consultar!","ERRO",0);
                }

            } catch (SQLException ex) {
                // Conexão com servidor mal sucedida
                JOptionPane.showMessageDialog(null,"Erro ao conectar com o servidor","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Código fora do formato
            JOptionPane.showMessageDialog(null,"Digite o código corretamante","ERRO",0);
            cod1_che.setText("");
        }
        
        
        
       //--------
    }//GEN-LAST:event_checkin_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField assento_che;
    private org.edisoncor.gui.button.ButtonIcon checkin_BTN;
    public static javax.swing.JTextField classe_che;
    private javax.swing.JTextField cod1_che;
    public static javax.swing.JTextField data_che;
    public static javax.swing.JTextField destino_che;
    public static javax.swing.JTextField hora_che;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel nome_che;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    public static javax.swing.JTextField partida_che;
    // End of variables declaration//GEN-END:variables
}
