/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Destino2_GUI extends javax.swing.JFrame {

    //------------
    static int cod;
    static String partidaI;
    static String destinoI;
    static String partidaV;
    static String destinoV;
    static String pasA;
    static String pasM;
    static String horaI;
    static String dataI;
    static String horaV;
    static String dataV;
    
    String url = "jdbc:mysql://localhost/VMAIRLANES"; // enderço do BD
    String username = "root";        //nome de um usuário de seu BD
    String password = "";  // senha do BD
    //-------------
    
    
    //código---
    
    public static DefaultTableModel  passagem_idavolta(ResultSet rs) {
        try {
           ResultSetMetaData metaData = rs.getMetaData();
         int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();
       // AS LINHAS ABAIXO SÃO REFERENTES AOS CAMPOS DA TABELA CLIENTE
            columnNames.addElement("Código");
            columnNames.addElement("Partida");
            columnNames.addElement("Destino");
            columnNames.addElement("Adultos");
            columnNames.addElement("Menores");
            columnNames.addElement("Hora");
            columnNames.addElement("Data");
         
            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
           return new DefaultTableModel(rows, columnNames);
       } catch (Exception e) {

           return null;
        }
        }

    
    //código---
    
    
    
    //codigo2---
    
    public void refresh(){
    
try{
   Connection conn;
          conn = (Connection) DriverManager.getConnection(url, username, password);
    //Controller.Conecta_BD.carregaDriver();
     
    
    System.out.println("realizado");
            String sql = "SELECT * FROM passagem_idavolta;";
PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
//ResultSet rs = pst.executeQuery();
//passagem_ida.setModel(passagem_ida(rs));
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}    
    } 

    
    //codigo2---
    
    
    
    public Destino2_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        apenasIda_BTN = new org.edisoncor.gui.button.ButtonIpod();
        horaVolta_TXT = new javax.swing.JTextField();
        dataVolta_TXT = new javax.swing.JTextField();
        pasM_TXT = new javax.swing.JTextField();
        destinoVolta_TXT = new javax.swing.JTextField();
        horaIda_TXT = new javax.swing.JTextField();
        partidaIda_TXT = new javax.swing.JTextField();
        destinoIda_TXT = new javax.swing.JTextField();
        partidaVolta_TXT = new javax.swing.JTextField();
        pasA_TXT = new javax.swing.JTextField();
        dataIda_TXT = new javax.swing.JTextField();
        EscolherClasse_BTN2 = new org.edisoncor.gui.button.ButtonSeven();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EscolherDestino_IdaVolta2.png"))); // NOI18N
        panelImage1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Adultos:");
        panelImage1.add(jLabel2);
        jLabel2.setBounds(20, 200, 50, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Menores:");
        panelImage1.add(jLabel3);
        jLabel3.setBounds(20, 250, 60, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Local de partida:");
        panelImage1.add(jLabel5);
        jLabel5.setBounds(230, 294, 260, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Seu destino:");
        panelImage1.add(jLabel6);
        jLabel6.setBounds(230, 350, 260, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Hora da volta:");
        panelImage1.add(jLabel4);
        jLabel4.setBounds(60, 350, 80, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Data da volta:");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(560, 240, 90, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Data da ida:");
        panelImage1.add(jLabel7);
        jLabel7.setBounds(560, 190, 70, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Local de partida:");
        panelImage1.add(jLabel8);
        jLabel8.setBounds(230, 190, 260, 14);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Seu destino:");
        panelImage1.add(jLabel9);
        jLabel9.setBounds(230, 240, 260, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("Hora da ida:");
        panelImage1.add(jLabel10);
        jLabel10.setBounds(60, 300, 80, 20);

        apenasIda_BTN.setText("    ");
        apenasIda_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apenasIda_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(apenasIda_BTN);
        apenasIda_BTN.setBounds(150, 120, 100, 50);
        panelImage1.add(horaVolta_TXT);
        horaVolta_TXT.setBounds(60, 370, 70, 20);
        panelImage1.add(dataVolta_TXT);
        dataVolta_TXT.setBounds(560, 260, 60, 20);
        panelImage1.add(pasM_TXT);
        pasM_TXT.setBounds(80, 250, 40, 20);
        panelImage1.add(destinoVolta_TXT);
        destinoVolta_TXT.setBounds(230, 370, 250, 20);
        panelImage1.add(horaIda_TXT);
        horaIda_TXT.setBounds(60, 320, 70, 20);
        panelImage1.add(partidaIda_TXT);
        partidaIda_TXT.setBounds(230, 210, 250, 20);
        panelImage1.add(destinoIda_TXT);
        destinoIda_TXT.setBounds(230, 260, 250, 20);
        panelImage1.add(partidaVolta_TXT);
        partidaVolta_TXT.setBounds(230, 320, 250, 20);
        panelImage1.add(pasA_TXT);
        pasA_TXT.setBounds(80, 200, 40, 20);
        panelImage1.add(dataIda_TXT);
        dataIda_TXT.setBounds(560, 210, 60, 20);

        EscolherClasse_BTN2.setText("Escolher Classe");
        EscolherClasse_BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolherClasse_BTN2ActionPerformed(evt);
            }
        });
        panelImage1.add(EscolherClasse_BTN2);
        EscolherClasse_BTN2.setBounds(510, 350, 130, 35);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 650, 400);

        setSize(new java.awt.Dimension(650, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EscolherClasse_BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolherClasse_BTN2ActionPerformed

        partidaI = partidaIda_TXT.getText();
        partidaV = partidaVolta_TXT.getText();
        destinoI = destinoIda_TXT.getText();
        destinoV = destinoVolta_TXT.getText();
        pasA = pasA_TXT.getText();
        pasM = pasM_TXT.getText();
        horaI = horaIda_TXT.getText();
        dataI = dataIda_TXT.getText();
        horaV = horaVolta_TXT.getText();
        dataV = dataVolta_TXT.getText();
        Controller.Conecta_BD.carregaDriver();
        try {

            Connection con = null;

            try {
                con = (Connection) DriverManager.getConnection(url, username, password);
            } catch (SQLException ex) {

                Logger.getLogger(Destino_GUI.class.getName()).log(Level.SEVERE, null, ex);

            }

            // Recebendo os dados a serem inseridos na tabela
            String sql = "INSERT INTO passagem_idavolta(partidaida_pas , partidavolta_pas , destinoida_pas , destinovolta_pas , num_adultos , num_menores , horaida_pas , dataida_pas , horavolta_pas , datavolta_pas) VALUES ('"+partidaI+"', '"+partidaV+"','"+destinoI+"','"+destinoV+"''"+pasA+"','"+pasM+"','"+horaI+"','"+dataI+"''"+horaV+"','"+dataV+"')";

            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção

                JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
                partidaIda_TXT.setText("");
                partidaVolta_TXT.setText("");
                destinoIda_TXT.setText("");
                destinoVolta_TXT.setText("");
                pasA_TXT.setText("");
                pasM_TXT.setText("");
                horaIda_TXT.setText("");
                dataIda_TXT.setText("");
                horaVolta_TXT.setText("");
                dataVolta_TXT.setText("");
                new Classes_GUI().setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
            partidaIda_TXT.setText("");
                partidaVolta_TXT.setText("");
                destinoIda_TXT.setText("");
                destinoVolta_TXT.setText("");
                pasA_TXT.setText("");
                pasM_TXT.setText("");
                horaIda_TXT.setText("");
                dataIda_TXT.setText("");
                horaVolta_TXT.setText("");
                dataVolta_TXT.setText("");
        }refresh();

    }//GEN-LAST:event_EscolherClasse_BTN2ActionPerformed

    private void apenasIda_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apenasIda_BTNActionPerformed
        new Destino_GUI().setVisible(true);
    }//GEN-LAST:event_apenasIda_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Destino2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Destino2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Destino2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Destino2_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Destino2_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonSeven EscolherClasse_BTN2;
    private org.edisoncor.gui.button.ButtonIpod apenasIda_BTN;
    public static javax.swing.JTextField dataIda_TXT;
    public static javax.swing.JTextField dataVolta_TXT;
    public static javax.swing.JTextField destinoIda_TXT;
    public static javax.swing.JTextField destinoVolta_TXT;
    public static javax.swing.JTextField horaIda_TXT;
    public static javax.swing.JTextField horaVolta_TXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    public static javax.swing.JTextField partidaIda_TXT;
    public static javax.swing.JTextField partidaVolta_TXT;
    private javax.swing.JTextField pasA_TXT;
    private javax.swing.JTextField pasM_TXT;
    // End of variables declaration//GEN-END:variables
}
