/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Destino_GUI extends javax.swing.JFrame {

    //------------
    static int cod;
    static String partida;
    static String destino;
    static String pasA;
    static String pasM;
    static String hora;
    static String data;
    
    String url = "jdbc:mysql://localhost/VMAIRLANES"; // enderço do BD
    String username = "root";        //nome de um usuário de seu BD
    String password = "";  // senha do BD
    //-------------
    
    
    //código---
    
    public static DefaultTableModel  passagem_ida(ResultSet rs) {
        try {
           ResultSetMetaData metaData = rs.getMetaData();
         int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();
       // AS LINHAS ABAIXO SÃO REFERENTES AOS CAMPOS DA TABELA CLIENTE
            columnNames.addElement("Código");
            columnNames.addElement("Partida");
            columnNames.addElement("Destino");
            columnNames.addElement("Adultos");
            columnNames.addElement("Menores");
            columnNames.addElement("Hora");
            columnNames.addElement("Data");
         
            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
           return new DefaultTableModel(rows, columnNames);
       } catch (Exception e) {

           return null;
        }
        }

    
    //código---
    
    
    
    //codigo2---
    
    public void refresh(){
    
try{
   Connection conn;
          conn = (Connection) DriverManager.getConnection(url, username, password);
    //Controller.Conecta_BD.carregaDriver();
     
    
    System.out.println("realizado");
            String sql = "SELECT * FROM passagem_ida;";
PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
ResultSet rs = pst.executeQuery();
//passagem_ida.setModel(passagem_ida(rs));
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}    
    } 

    
    //codigo2---
    
    
    public Destino_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        EscolherClasse_BTN = new org.edisoncor.gui.button.ButtonSeven();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        destino_TXT = new javax.swing.JTextField();
        passA_TXT = new javax.swing.JTextField();
        passM_TXT = new javax.swing.JTextField();
        partida_TXT = new javax.swing.JTextField();
        hora_TXT = new javax.swing.JTextField();
        data_TXT = new javax.swing.JTextField();
        buttonIpod1 = new org.edisoncor.gui.button.ButtonIpod();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EscolherDestino_Ida.png"))); // NOI18N
        panelImage1.setLayout(null);

        EscolherClasse_BTN.setText("Escolher Classe");
        EscolherClasse_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolherClasse_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(EscolherClasse_BTN);
        EscolherClasse_BTN.setBounds(510, 350, 130, 35);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Data:");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(560, 190, 40, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Adultos:");
        panelImage1.add(jLabel2);
        jLabel2.setBounds(20, 200, 50, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Menores:");
        panelImage1.add(jLabel3);
        jLabel3.setBounds(20, 250, 60, 14);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Hora da ida:");
        panelImage1.add(jLabel4);
        jLabel4.setBounds(50, 330, 80, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Local de partida:");
        panelImage1.add(jLabel5);
        jLabel5.setBounds(220, 190, 260, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Seu destino:");
        panelImage1.add(jLabel6);
        jLabel6.setBounds(220, 240, 260, 14);
        panelImage1.add(destino_TXT);
        destino_TXT.setBounds(220, 260, 250, 20);
        panelImage1.add(passA_TXT);
        passA_TXT.setBounds(80, 200, 50, 30);
        panelImage1.add(passM_TXT);
        passM_TXT.setBounds(80, 250, 50, 30);
        panelImage1.add(partida_TXT);
        partida_TXT.setBounds(220, 210, 250, 20);
        panelImage1.add(hora_TXT);
        hora_TXT.setBounds(50, 350, 90, 20);
        panelImage1.add(data_TXT);
        data_TXT.setBounds(560, 210, 70, 20);

        buttonIpod1.setText("   ");
        buttonIpod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIpod1ActionPerformed(evt);
            }
        });
        panelImage1.add(buttonIpod1);
        buttonIpod1.setBounds(250, 120, 120, 40);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 650, 400);

        setSize(new java.awt.Dimension(650, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EscolherClasse_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolherClasse_BTNActionPerformed
 
        partida = partida_TXT.getText();
        destino = destino_TXT.getText();
        pasA = passA_TXT.getText();
        pasM = passM_TXT.getText();
        hora = hora_TXT.getText();
        data = data_TXT.getText();
       Controller.Conecta_BD.carregaDriver();
        try { 
               
        Connection con = null;
            
            
    try {
    con = (Connection) DriverManager.getConnection(url, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(Destino_GUI.class.getName()).log(Level.SEVERE, null, ex);

            
                   }

            // Recebendo os dados a serem inseridos na tabela
            String sql = "INSERT INTO passagem_ida(partida_pas , destino_pas , num_adultos , num_menores , hora_pas , data_pas) VALUES ('"+partida+"','"+destino+"','"+pasA+"','"+pasM+"','"+hora+"','"+data+"')";
     
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção

  JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
                partida_TXT.setText("");
                destino_TXT.setText("");
                passA_TXT.setText("");
                passM_TXT.setText("");
                hora_TXT.setText("");
                data_TXT.setText("");
                new Classes_GUI().setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!","ERRO!",0);
            }

        }catch(NumberFormatException erro){
        // Tratamento de erro caso o usuario não digite o telefone corretamente
        JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
        partida_TXT.setText("");
                destino_TXT.setText("");
                passA_TXT.setText("");
                passM_TXT.setText("");
                hora_TXT.setText("");
                data_TXT.setText("");
}refresh();
        
        
        
        
        
        
    }//GEN-LAST:event_EscolherClasse_BTNActionPerformed

    private void buttonIpod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIpod1ActionPerformed
        new Destino2_GUI().setVisible(true);
    }//GEN-LAST:event_buttonIpod1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Destino_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Destino_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Destino_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Destino_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Destino_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonSeven EscolherClasse_BTN;
    private org.edisoncor.gui.button.ButtonIpod buttonIpod1;
    public static javax.swing.JTextField data_TXT;
    public static javax.swing.JTextField destino_TXT;
    public static javax.swing.JTextField hora_TXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    public static javax.swing.JTextField partida_TXT;
    public static javax.swing.JTextField passA_TXT;
    public static javax.swing.JTextField passM_TXT;
    // End of variables declaration//GEN-END:variables
}
