/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Pichau
 */
public class economica_GUI extends javax.swing.JFrame {

    /**
     * Creates new form a_GUI
     */
    public economica_GUI() {
        initComponents();
        
        ocupado1_IMG.setVisible(false);
        ocupado2_IMG.setVisible(false);
        ocupado3_IMG.setVisible(false);
        ocupado4_IMG.setVisible(false);
        ocupado5_IMG.setVisible(false);
        ocupado6_IMG.setVisible(false);
        ocupado7_IMG.setVisible(false);
        ocupado8_IMG.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        ec1_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ec3_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ec5_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ec7_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ec2_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ec4_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ec6_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ec8_BTN = new org.edisoncor.gui.button.ButtonIpod();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ocupado1_IMG = new javax.swing.JLabel();
        ocupado2_IMG = new javax.swing.JLabel();
        ocupado3_IMG = new javax.swing.JLabel();
        ocupado4_IMG = new javax.swing.JLabel();
        ocupado5_IMG = new javax.swing.JLabel();
        ocupado6_IMG = new javax.swing.JLabel();
        ocupado7_IMG = new javax.swing.JLabel();
        ocupado8_IMG = new javax.swing.JLabel();
        fina1_BTN = new org.edisoncor.gui.button.ButtonSeven();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EA(c.e).png"))); // NOI18N
        panelImage1.setLayout(null);

        ec1_BTN.setText("    ");
        ec1_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec1_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ec1_BTN);
        ec1_BTN.setBounds(20, 180, 30, 20);

        ec3_BTN.setText("    ");
        ec3_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec3_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ec3_BTN);
        ec3_BTN.setBounds(70, 180, 30, 20);

        ec5_BTN.setText("    ");
        ec5_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec5_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ec5_BTN);
        ec5_BTN.setBounds(120, 180, 30, 20);

        ec7_BTN.setText("    ");
        ec7_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec7_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ec7_BTN);
        ec7_BTN.setBounds(180, 180, 30, 20);

        ec2_BTN.setText("    ");
        ec2_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec2_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ec2_BTN);
        ec2_BTN.setBounds(20, 220, 30, 20);

        ec4_BTN.setText("    ");
        ec4_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec4_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ec4_BTN);
        ec4_BTN.setBounds(60, 220, 30, 20);

        ec6_BTN.setText("    ");
        ec6_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec6_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ec6_BTN);
        ec6_BTN.setBounds(110, 220, 30, 20);

        ec8_BTN.setText("    ");
        ec8_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec8_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ec8_BTN);
        ec8_BTN.setBounds(170, 220, 30, 20);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("2");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(20, 220, 20, 20);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("8");
        panelImage1.add(jLabel2);
        jLabel2.setBounds(180, 220, 20, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("1");
        panelImage1.add(jLabel3);
        jLabel3.setBounds(20, 170, 20, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("3");
        panelImage1.add(jLabel4);
        jLabel4.setBounds(70, 180, 20, 20);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("4");
        panelImage1.add(jLabel5);
        jLabel5.setBounds(70, 220, 20, 20);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("5");
        panelImage1.add(jLabel6);
        jLabel6.setBounds(120, 180, 30, 20);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("6");
        panelImage1.add(jLabel7);
        jLabel7.setBounds(120, 220, 30, 20);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("7");
        panelImage1.add(jLabel8);
        jLabel8.setBounds(180, 180, 20, 20);

        ocupado1_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado1_IMG);
        ocupado1_IMG.setBounds(10, 170, 40, 40);

        ocupado2_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado2_IMG);
        ocupado2_IMG.setBounds(10, 210, 40, 40);

        ocupado3_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado3_IMG);
        ocupado3_IMG.setBounds(60, 170, 40, 40);

        ocupado4_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado4_IMG);
        ocupado4_IMG.setBounds(60, 210, 40, 40);

        ocupado5_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado5_IMG);
        ocupado5_IMG.setBounds(110, 170, 40, 40);

        ocupado6_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado6_IMG);
        ocupado6_IMG.setBounds(110, 210, 40, 40);

        ocupado7_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado7_IMG);
        ocupado7_IMG.setBounds(170, 170, 40, 40);

        ocupado8_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado8_IMG);
        ocupado8_IMG.setBounds(170, 210, 40, 40);

        fina1_BTN.setText("Finalizar");
        fina1_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fina1_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(fina1_BTN);
        fina1_BTN.setBounds(50, 320, 116, 35);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 650, 400);

        jMenu1.setText("Voltar");

        jMenuItem1.setText("Escolher classes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(650, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     new Classes_GUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ec1_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec1_BTNActionPerformed
        ocupado1_IMG.setVisible(true);
    }//GEN-LAST:event_ec1_BTNActionPerformed

    private void ec2_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec2_BTNActionPerformed
        ocupado2_IMG.setVisible(true);
    }//GEN-LAST:event_ec2_BTNActionPerformed

    private void ec3_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec3_BTNActionPerformed
        ocupado3_IMG.setVisible(true);
    }//GEN-LAST:event_ec3_BTNActionPerformed

    private void ec4_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec4_BTNActionPerformed
       ocupado4_IMG.setVisible(true);
    }//GEN-LAST:event_ec4_BTNActionPerformed

    private void ec5_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec5_BTNActionPerformed
        ocupado5_IMG.setVisible(true);
    }//GEN-LAST:event_ec5_BTNActionPerformed

    private void ec6_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec6_BTNActionPerformed
        ocupado6_IMG.setVisible(true);
    }//GEN-LAST:event_ec6_BTNActionPerformed

    private void ec7_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec7_BTNActionPerformed
        ocupado7_IMG.setVisible(true);
    }//GEN-LAST:event_ec7_BTNActionPerformed

    private void ec8_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec8_BTNActionPerformed
       ocupado8_IMG.setVisible(true);
    }//GEN-LAST:event_ec8_BTNActionPerformed

    private void fina1_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fina1_BTNActionPerformed
        new Login_GUI().setVisible(true);
    }//GEN-LAST:event_fina1_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(economica_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(economica_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(economica_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(economica_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new economica_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIpod ec1_BTN;
    private org.edisoncor.gui.button.ButtonIpod ec2_BTN;
    private org.edisoncor.gui.button.ButtonIpod ec3_BTN;
    private org.edisoncor.gui.button.ButtonIpod ec4_BTN;
    private org.edisoncor.gui.button.ButtonIpod ec5_BTN;
    private org.edisoncor.gui.button.ButtonIpod ec6_BTN;
    private org.edisoncor.gui.button.ButtonIpod ec7_BTN;
    private org.edisoncor.gui.button.ButtonIpod ec8_BTN;
    private org.edisoncor.gui.button.ButtonSeven fina1_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel ocupado1_IMG;
    private javax.swing.JLabel ocupado2_IMG;
    private javax.swing.JLabel ocupado3_IMG;
    private javax.swing.JLabel ocupado4_IMG;
    private javax.swing.JLabel ocupado5_IMG;
    private javax.swing.JLabel ocupado6_IMG;
    private javax.swing.JLabel ocupado7_IMG;
    private javax.swing.JLabel ocupado8_IMG;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
