/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Pichau
 */
public class economicaPR_GUI extends javax.swing.JFrame {

    /**
     * Creates new form economicaPR_GUI
     */
    public economicaPR_GUI() {
        initComponents();
        ocupado1_IMG.setVisible(false);
        ocupado2_IMG.setVisible(false);
        ocupado3_IMG.setVisible(false);
        ocupado4_IMG.setVisible(false);
        ocupado5_IMG.setVisible(false);
        ocupado6_IMG.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        ecp6_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ecp1_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ecp3_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ecp5_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ecp2_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ecp4_BTN = new org.edisoncor.gui.button.ButtonIpod();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ocupado1_IMG = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ocupado3_IMG = new javax.swing.JLabel();
        ocupado5_IMG = new javax.swing.JLabel();
        ocupado2_IMG = new javax.swing.JLabel();
        ocupado4_IMG = new javax.swing.JLabel();
        ocupado6_IMG = new javax.swing.JLabel();
        fina2_BTN = new org.edisoncor.gui.button.ButtonSeven();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar6.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar6.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar7.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar7.add(jMenu14);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EA(c.ep).png"))); // NOI18N
        panelImage1.setLayout(null);

        ecp6_BTN.setText("    ");
        ecp6_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecp6_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ecp6_BTN);
        ecp6_BTN.setBounds(390, 220, 30, 20);

        ecp1_BTN.setText("    ");
        ecp1_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecp1_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ecp1_BTN);
        ecp1_BTN.setBounds(240, 170, 30, 20);

        ecp3_BTN.setText("    ");
        ecp3_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecp3_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ecp3_BTN);
        ecp3_BTN.setBounds(310, 170, 30, 20);

        ecp5_BTN.setText("    ");
        ecp5_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecp5_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ecp5_BTN);
        ecp5_BTN.setBounds(390, 170, 30, 20);

        ecp2_BTN.setText("    ");
        ecp2_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecp2_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ecp2_BTN);
        ecp2_BTN.setBounds(240, 210, 30, 20);

        ecp4_BTN.setText("    ");
        ecp4_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecp4_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(ecp4_BTN);
        ecp4_BTN.setBounds(310, 220, 30, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("6");
        panelImage1.add(jLabel3);
        jLabel3.setBounds(400, 210, 20, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("1");
        panelImage1.add(jLabel4);
        jLabel4.setBounds(240, 160, 20, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("3");
        panelImage1.add(jLabel5);
        jLabel5.setBounds(320, 160, 20, 30);

        ocupado1_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado1_IMG);
        ocupado1_IMG.setBounds(230, 160, 40, 40);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("5");
        panelImage1.add(jLabel6);
        jLabel6.setBounds(400, 160, 20, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("2");
        panelImage1.add(jLabel7);
        jLabel7.setBounds(240, 210, 20, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("4");
        panelImage1.add(jLabel8);
        jLabel8.setBounds(320, 210, 20, 30);

        ocupado3_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado3_IMG);
        ocupado3_IMG.setBounds(300, 160, 40, 40);

        ocupado5_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado5_IMG);
        ocupado5_IMG.setBounds(380, 160, 40, 40);

        ocupado2_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado2_IMG);
        ocupado2_IMG.setBounds(230, 200, 40, 50);

        ocupado4_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado4_IMG);
        ocupado4_IMG.setBounds(300, 210, 40, 40);

        ocupado6_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado6_IMG);
        ocupado6_IMG.setBounds(380, 210, 40, 40);

        fina2_BTN.setText("Finalizar");
        fina2_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fina2_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(fina2_BTN);
        fina2_BTN.setBounds(270, 330, 116, 35);

        jMenu3.setText("Voltar");

        jMenuItem1.setText("Classes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(650, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ecp6_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecp6_BTNActionPerformed
        ocupado6_IMG.setVisible(true);
    }//GEN-LAST:event_ecp6_BTNActionPerformed

    private void ecp1_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecp1_BTNActionPerformed
        ocupado1_IMG.setVisible(true);
    }//GEN-LAST:event_ecp1_BTNActionPerformed

    private void ecp3_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecp3_BTNActionPerformed
        ocupado3_IMG.setVisible(true);
    }//GEN-LAST:event_ecp3_BTNActionPerformed

    private void ecp5_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecp5_BTNActionPerformed
        ocupado5_IMG.setVisible(true);
    }//GEN-LAST:event_ecp5_BTNActionPerformed

    private void ecp2_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecp2_BTNActionPerformed
        ocupado2_IMG.setVisible(true);
    }//GEN-LAST:event_ecp2_BTNActionPerformed

    private void ecp4_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecp4_BTNActionPerformed
       ocupado4_IMG.setVisible(true);
    }//GEN-LAST:event_ecp4_BTNActionPerformed

    private void fina2_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fina2_BTNActionPerformed
        new Login_GUI().setVisible(true);
    }//GEN-LAST:event_fina2_BTNActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         new Classes_GUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(economicaPR_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(economicaPR_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(economicaPR_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(economicaPR_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new economicaPR_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIpod ecp1_BTN;
    private org.edisoncor.gui.button.ButtonIpod ecp2_BTN;
    private org.edisoncor.gui.button.ButtonIpod ecp3_BTN;
    private org.edisoncor.gui.button.ButtonIpod ecp4_BTN;
    private org.edisoncor.gui.button.ButtonIpod ecp5_BTN;
    private org.edisoncor.gui.button.ButtonIpod ecp6_BTN;
    private org.edisoncor.gui.button.ButtonSeven fina2_BTN;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel ocupado1_IMG;
    private javax.swing.JLabel ocupado2_IMG;
    private javax.swing.JLabel ocupado3_IMG;
    private javax.swing.JLabel ocupado4_IMG;
    private javax.swing.JLabel ocupado5_IMG;
    private javax.swing.JLabel ocupado6_IMG;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
