/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Pichau
 */
public class executiva_GUI extends javax.swing.JFrame {

    /**
     * Creates new form executiva_GUI
     */
    public executiva_GUI() {
        initComponents();
        
        
        ocupado1_IMG.setVisible(false);
        ocupado2_IMG.setVisible(false);
        ocupado3_IMG.setVisible(false);
        ocupado4_IMG.setVisible(false);
        ocupado5_IMG.setVisible(false);
        ocupado6_IMG.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        exe4_BTN = new org.edisoncor.gui.button.ButtonIpod();
        exe1_BTN = new org.edisoncor.gui.button.ButtonIpod();
        exe3_BTN = new org.edisoncor.gui.button.ButtonIpod();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        exe6_BTN = new org.edisoncor.gui.button.ButtonIpod();
        exe5_BTN = new org.edisoncor.gui.button.ButtonIpod();
        exe2_BTN = new org.edisoncor.gui.button.ButtonIpod();
        ocupado1_IMG = new javax.swing.JLabel();
        ocupado3_IMG = new javax.swing.JLabel();
        ocupado5_IMG = new javax.swing.JLabel();
        ocupado2_IMG = new javax.swing.JLabel();
        ocupado4_IMG = new javax.swing.JLabel();
        ocupado6_IMG = new javax.swing.JLabel();
        fina3_BTN = new org.edisoncor.gui.button.ButtonSeven();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EA(c.Ex).png"))); // NOI18N
        panelImage1.setLayout(null);

        exe4_BTN.setText("    ");
        exe4_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exe4_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(exe4_BTN);
        exe4_BTN.setBounds(530, 230, 30, 20);

        exe1_BTN.setText("    ");
        exe1_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exe1_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(exe1_BTN);
        exe1_BTN.setBounds(460, 180, 30, 20);

        exe3_BTN.setText("    ");
        exe3_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exe3_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(exe3_BTN);
        exe3_BTN.setBounds(530, 180, 30, 20);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("6");
        panelImage1.add(jLabel7);
        jLabel7.setBounds(600, 230, 30, 20);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("1");
        panelImage1.add(jLabel8);
        jLabel8.setBounds(460, 180, 30, 20);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("3");
        panelImage1.add(jLabel9);
        jLabel9.setBounds(530, 180, 30, 20);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("5");
        panelImage1.add(jLabel10);
        jLabel10.setBounds(600, 180, 30, 20);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("2");
        panelImage1.add(jLabel11);
        jLabel11.setBounds(460, 230, 30, 20);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("4");
        panelImage1.add(jLabel12);
        jLabel12.setBounds(530, 230, 30, 20);

        exe6_BTN.setText("    ");
        exe6_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exe6_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(exe6_BTN);
        exe6_BTN.setBounds(600, 230, 30, 20);

        exe5_BTN.setText("    ");
        exe5_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exe5_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(exe5_BTN);
        exe5_BTN.setBounds(600, 180, 30, 20);

        exe2_BTN.setText("    ");
        exe2_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exe2_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(exe2_BTN);
        exe2_BTN.setBounds(460, 230, 30, 20);

        ocupado1_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado1_IMG);
        ocupado1_IMG.setBounds(450, 170, 40, 40);

        ocupado3_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado3_IMG);
        ocupado3_IMG.setBounds(520, 170, 40, 40);

        ocupado5_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado5_IMG);
        ocupado5_IMG.setBounds(590, 170, 40, 40);

        ocupado2_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado2_IMG);
        ocupado2_IMG.setBounds(450, 220, 40, 40);

        ocupado4_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado4_IMG);
        ocupado4_IMG.setBounds(520, 220, 40, 40);

        ocupado6_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ocupado.png"))); // NOI18N
        panelImage1.add(ocupado6_IMG);
        ocupado6_IMG.setBounds(590, 220, 40, 40);

        fina3_BTN.setText("Finalizar");
        fina3_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fina3_BTNActionPerformed(evt);
            }
        });
        panelImage1.add(fina3_BTN);
        fina3_BTN.setBounds(490, 330, 116, 35);

        getContentPane().add(panelImage1);
        panelImage1.setBounds(0, 0, 650, 400);

        jMenu1.setText("Voltar");

        jMenuItem1.setText("Escolher classes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(650, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         new Classes_GUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void exe4_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exe4_BTNActionPerformed
        ocupado4_IMG.setVisible(true);
    }//GEN-LAST:event_exe4_BTNActionPerformed

    private void exe1_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exe1_BTNActionPerformed
        ocupado1_IMG.setVisible(false);
    }//GEN-LAST:event_exe1_BTNActionPerformed

    private void exe3_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exe3_BTNActionPerformed
        ocupado3_IMG.setVisible(false);
    }//GEN-LAST:event_exe3_BTNActionPerformed

    private void exe6_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exe6_BTNActionPerformed
        ocupado6_IMG.setVisible(false);
    }//GEN-LAST:event_exe6_BTNActionPerformed

    private void exe5_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exe5_BTNActionPerformed
       ocupado5_IMG.setVisible(false);
    }//GEN-LAST:event_exe5_BTNActionPerformed

    private void exe2_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exe2_BTNActionPerformed
        ocupado2_IMG.setVisible(false);
    }//GEN-LAST:event_exe2_BTNActionPerformed

    private void fina3_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fina3_BTNActionPerformed
        new Login_GUI().setVisible(true);
    }//GEN-LAST:event_fina3_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(executiva_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(executiva_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(executiva_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(executiva_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new executiva_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIpod exe1_BTN;
    private org.edisoncor.gui.button.ButtonIpod exe2_BTN;
    private org.edisoncor.gui.button.ButtonIpod exe3_BTN;
    private org.edisoncor.gui.button.ButtonIpod exe4_BTN;
    private org.edisoncor.gui.button.ButtonIpod exe5_BTN;
    private org.edisoncor.gui.button.ButtonIpod exe6_BTN;
    private org.edisoncor.gui.button.ButtonSeven fina3_BTN;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel ocupado1_IMG;
    private javax.swing.JLabel ocupado2_IMG;
    private javax.swing.JLabel ocupado3_IMG;
    private javax.swing.JLabel ocupado4_IMG;
    private javax.swing.JLabel ocupado5_IMG;
    private javax.swing.JLabel ocupado6_IMG;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
