/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.itextpdf.text.DocumentException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class FinalizarC_GUI extends javax.swing.JFrame {

   
    //------------
    static int cpf;
    static String nom;
    String url = "jdbc:mysql://localhost/VMAIRLANES"; // enderço do BD
    String username = "root";        //nome de um usuário de seu BD
    String password = "";  // senha do BD
    //-------------
    
    
    //código---
    
    public static DefaultTableModel  clientes(ResultSet rs) {
        try {
           ResultSetMetaData metaData = rs.getMetaData();
         int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();
       // AS LINHAS ABAIXO SÃO REFERENTES AOS CAMPOS DA TABELA CLIENTE
            columnNames.addElement("Código");
            columnNames.addElement("Nome");
            columnNames.addElement("email");
            columnNames.addElement("CPF");
         
            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
           return new DefaultTableModel(rows, columnNames);
       } catch (Exception e) {

           return null;
        }
        }

    
    //código---
    
    
    //codigo2---
    
    public void refresh(){
    
try{
   Connection conn;
          conn = (Connection) DriverManager.getConnection(url, username, password);
    //Controller.Conecta_BD.carregaDriver();
     
    
    System.out.println("realizado");
            String sql = "SELECT * FROM clientes;";
PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
ResultSet rs = pst.executeQuery();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}    
    } 

    
    //codigo2---
    
    
    public FinalizarC_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        cliente_BTN = new org.edisoncor.gui.button.ButtonIcon();
        calcular_BTN = new org.edisoncor.gui.button.ButtonSeven();
        jLabel2 = new javax.swing.JLabel();
        valorT_pas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        assento_pas = new javax.swing.JTextField();
        cpf_pas = new javax.swing.JTextField();
        nome_pas = new javax.swing.JTextField();
        bag_pas = new javax.swing.JTextField();
        classe_pas = new javax.swing.JTextField();
        imprimir_BTN = new org.edisoncor.gui.button.ButtonSeven();
        pagar_BTN = new org.edisoncor.gui.button.ButtonSeven();
        voltar_BTN = new org.edisoncor.gui.button.ButtonSeven();
        buttonSeven1 = new org.edisoncor.gui.button.ButtonSeven();
        buttonSeven2 = new org.edisoncor.gui.button.ButtonSeven();

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/finalizarTela.png"))); // NOI18N
        panelImage2.setLayout(null);

        cliente_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cliente.png"))); // NOI18N
        cliente_BTN.setText("buttonIcon1");
        cliente_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente_BTNActionPerformed(evt);
            }
        });
        panelImage2.add(cliente_BTN);
        cliente_BTN.setBounds(270, 110, 40, 40);

        calcular_BTN.setText("Calcular Valor Final");
        calcular_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_BTNActionPerformed(evt);
            }
        });
        panelImage2.add(calcular_BTN);
        calcular_BTN.setBounds(270, 300, 170, 35);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Valor Final:");
        panelImage2.add(jLabel2);
        jLabel2.setBounds(460, 280, 130, 20);

        valorT_pas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        valorT_pas.setForeground(new java.awt.Color(0, 153, 51));
        panelImage2.add(valorT_pas);
        valorT_pas.setBounds(460, 300, 140, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Bagagens a mais:");
        panelImage2.add(jLabel3);
        jLabel3.setBounds(410, 110, 120, 14);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("CPF:");
        panelImage2.add(jLabel4);
        jLabel4.setBounds(60, 110, 27, 15);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Cliente:");
        panelImage2.add(jLabel5);
        jLabel5.setBounds(60, 160, 50, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Classe:");
        panelImage2.add(jLabel6);
        jLabel6.setBounds(60, 240, 50, 14);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Assento:");
        panelImage2.add(jLabel7);
        jLabel7.setBounds(60, 294, 50, 20);

        assento_pas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panelImage2.add(assento_pas);
        assento_pas.setBounds(70, 313, 80, 20);

        cpf_pas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panelImage2.add(cpf_pas);
        cpf_pas.setBounds(70, 130, 170, 23);

        nome_pas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panelImage2.add(nome_pas);
        nome_pas.setBounds(70, 180, 170, 23);

        bag_pas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panelImage2.add(bag_pas);
        bag_pas.setBounds(410, 130, 120, 23);

        classe_pas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panelImage2.add(classe_pas);
        classe_pas.setBounds(70, 260, 130, 20);

        imprimir_BTN.setText("Imprimir");
        imprimir_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimir_BTNActionPerformed(evt);
            }
        });
        panelImage2.add(imprimir_BTN);
        imprimir_BTN.setBounds(490, 350, 116, 35);

        pagar_BTN.setText("Pagar");
        pagar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagar_BTNActionPerformed(evt);
            }
        });
        panelImage2.add(pagar_BTN);
        pagar_BTN.setBounds(370, 350, 116, 35);

        voltar_BTN.setForeground(new java.awt.Color(0, 0, 0));
        voltar_BTN.setText("<-");
        voltar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_BTNActionPerformed(evt);
            }
        });
        panelImage2.add(voltar_BTN);
        voltar_BTN.setBounds(50, 60, 40, 30);

        buttonSeven1.setText("Check-in Ida e volta");
        buttonSeven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven1ActionPerformed(evt);
            }
        });
        panelImage2.add(buttonSeven1);
        buttonSeven1.setBounds(210, 350, 150, 35);

        buttonSeven2.setText("Check-in Ida");
        buttonSeven2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven2ActionPerformed(evt);
            }
        });
        panelImage2.add(buttonSeven2);
        buttonSeven2.setBounds(90, 350, 116, 35);

        getContentPane().add(panelImage2);
        panelImage2.setBounds(0, 0, 650, 400);

        setSize(new java.awt.Dimension(650, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cliente_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente_BTNActionPerformed
        //--------
        
        
        
        try{     //Iniciando o possivel tratamento de erros
            //Declarando a variavel código
            int cpf = Integer.valueOf(cpf_pas.getText());
            Controller.Conecta_BD.carregaDriver(); // Carregando o driver
            try {// Tratamento de erro para a conexao
                // Declarando  a variavel de conexão con
                // e estabelendo a conexão
                Connection con = null;

                try {
                    con = (Connection) DriverManager.getConnection(url, username, password);
                } catch (SQLException ex) {
                    Logger.getLogger(FinalizarC_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }

                // Declarando uma string com o comando mySQL para consulta
                String sql = "SELECT nome_cli FROM clientes where cpf_cli = "+cpf;
                // Criando variavel que executara o comando da string sql
                Statement stm = (Statement) con.createStatement();
                try//Tratamento de erro da consulta
                { //Criando variavel que exibira os resultados
                    //Executando o comando da string sql na variavel rs
                    ResultSet rs = stm.executeQuery(sql);

                    int i=0; // Variavel utilizada para saber se ha dados cadastrados

                    while (rs.next()) {  // Criando variaveis que receberão os valores do banco de dados
                        String nome = rs.getString("nome_cli");

                        i++;

                        //JOptionPane.showMessageDialog(null,"Nome: " + nome + "\nEmail: " +email + "\nTelefone: " +telefone, "Resultado",-1);
                        nome_pas.setText(String.valueOf(nome));
                        

                    }

                    if(i==0){ // Verificando se ha dados cadastrados atraves da variavel i

                        JOptionPane.showMessageDialog(null,"Dado não cadastrado","Resultado",-1);

                    }

                } catch (Exception ex) { // Consulta mal sucedida
                    JOptionPane.showMessageDialog(null,"\nErro ao consultar!","ERRO",0);
                }

            } catch (SQLException ex) {
                // Conexão com servidor mal sucedida
                JOptionPane.showMessageDialog(null,"Erro ao conectar com o servidor","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Código fora do formato
            JOptionPane.showMessageDialog(null,"Digite o código corretamante","ERRO",0);
            cpf_pas.setText("");
        }
        
        
        
       //--------
    }//GEN-LAST:event_cliente_BTNActionPerformed

    private void calcular_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_BTNActionPerformed
        Model.Funcionalidades_DAO.Finalizar();
    }//GEN-LAST:event_calcular_BTNActionPerformed

    private void pagar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagar_BTNActionPerformed
        Model.Funcionalidades_DAO.pagamento();
    }//GEN-LAST:event_pagar_BTNActionPerformed

    private void imprimir_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimir_BTNActionPerformed
        try {
            Model.Funcionalidades_DAO.imprimir();
        } catch (DocumentException ex) {
            Logger.getLogger(FinalizarC_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FinalizarC_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imprimir_BTNActionPerformed

    private void voltar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_BTNActionPerformed
        new Classes_GUI().setVisible(true);
    }//GEN-LAST:event_voltar_BTNActionPerformed

    private void buttonSeven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven1ActionPerformed
        new CheckIn2_GUI().setVisible(true);
    }//GEN-LAST:event_buttonSeven1ActionPerformed

    private void buttonSeven2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven2ActionPerformed
        new CheckIn_GUI().setVisible(true);
    }//GEN-LAST:event_buttonSeven2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizarC_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField assento_pas;
    public static javax.swing.JTextField bag_pas;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven1;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven2;
    private org.edisoncor.gui.button.ButtonSeven calcular_BTN;
    public static javax.swing.JTextField classe_pas;
    private org.edisoncor.gui.button.ButtonIcon cliente_BTN;
    public static javax.swing.JTextField cpf_pas;
    private org.edisoncor.gui.button.ButtonSeven imprimir_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JTextField nome_pas;
    private org.edisoncor.gui.button.ButtonSeven pagar_BTN;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    public static javax.swing.JTextField valorT_pas;
    private org.edisoncor.gui.button.ButtonSeven voltar_BTN;
    // End of variables declaration//GEN-END:variables
}
