/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alunos
 */


    /**
     * Creates new form Splash_GUI
     */
   public class Splash_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Splash_GUI
     */
    public Splash_GUI() {
        initComponents();
        iniciarSplash();
    }

    private void iniciarSplash() {
        new Thread() {
            public void run() {
                for (int i = 0; i <= 100; i++) {
                    try {
                        sleep(60);
                        progress.setValue(i);

                        if (i == 10) {
                            porcentagem.setText(i + " %");
                            label.setText("Fazendo a conexao com o banco de dados");
                            sleep(2000);

                        } else if (i <= 30) {
                            porcentagem.setText(i + " %");
                            label.setText("Carregando o sistema");
                            sleep(100);
                        } else if (i <= 99) {
                            label.setText("Carregamento quase completo");
                            porcentagem.setText(i + " %");
                        } else {
                            label.setText("Carregamento completo. Seu programa sera iniciado.");
                            porcentagem.setText(i + " %");
                            sleep(3000);

                            // Fecha o Splash Screen
                            dispose();

                            // Abre a próxima página
                            java.awt.EventQueue.invokeLater(new Runnable() {
                                public void run() {
                                    new Destino_GUI().setVisible(true);
                                }
                            });
                        }
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Splash_GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }.start();
    }

    // Outros métodos e variáveis omitidos para brevidade


        //-----> fim código splash
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress = new javax.swing.JProgressBar();
        label = new javax.swing.JLabel();
        porcentagem = new javax.swing.JLabel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(progress);
        progress.setBounds(180, 270, 290, 14);

        label.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        getContentPane().add(label);
        label.setBounds(220, 290, 290, 20);

        porcentagem.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        porcentagem.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(porcentagem);
        porcentagem.setBounds(310, 340, 40, 20);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Splash.png"))); // NOI18N
        getContentPane().add(panelImage2);
        panelImage2.setBounds(0, 0, 650, 400);

        setSize(new java.awt.Dimension(650, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash_GUI().setVisible(true);
                  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    public static javax.swing.JLabel porcentagem;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
